FROM node:16 as base

WORKDIR /app

COPY /app/package.json .
COPY /app/package-lock.json .

FROM base as test
RUN npm ci
COPY /app .
EXPOSE 3000
CMD [ "npm","test" ]

FROM base as prod
RUN npm ci --production
COPY /app .
EXPOSE 3000
CMD [ "npm","start" ]